apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: contact-postgres-pvc
spec:
    accessModes:
        - ReadWriteOnce
    resources:
        requests:
            storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: contact-postgress-deployment
spec:
    strategy:
        type: Recreate
    selector:
        matchLabels:
            app: contact_db
    template:
        metadata:
            labels:
                app: contact_db
        spec:   
            containers:
                - image: postgres:12.1
                  name: postgresql
                  env:
                      - name: POSTGRES_USER
                        valueFrom:
                            configMapKeyRef:
                                name: contact-config
                                key: CONTACT_POSTGRES_USER

                      - name: POSTGRES_PASSWORD
                        valueFrom:
                            secretKeyRef:
                                name: contact-secret
                                key: CONTACT_POSTGRES_PASSWORD
                                
                      - name: POSTGRES_DB
                        value: contacts

                  ports:
                    - containerPort: 5432
                      name: postgresport

                  volumeMounts:
                      - name: pgdata
                        mountPath: /var/lib/postgresql/data                      
            volumes:
                - name: pgdata
                  persistentVolumeClaim:
                        claimName: contact-postgres-pvc
---
apiVersion: v1
kind: Service
metadata:
    name: contact-db-svc
spec:
    ports:
        - port: 5432
          targetPort: 5432
    selector:
        app: contact_db
---
apiVersion: v1
kind: Service
metadata:
    name: contact-postgress-node-port
spec:
    type: NodePort
    ports:
        - port: 5432
          targetPort: 5432
          nodePort: 30126
    selector:
        app: contact_db
